# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - group: Test-vars
steps:

# - task: AzureResourceManagerTemplateDeployment@3
#   #condition: and(succeed(), eq('${{parameters.doSql}}', 'true'))
#   displayName: "Create ${{ parameters.ServiceReleased}}"
#   inputs:
#     deploymentScope: 'Resource Group'
#     azureResourceManagerConnection: ${{ parameters.ServiceConnection }}
#     subscriptionId: ${{ parameters.SubscriptionId }}
#     action: 'Create Or Update Resource Group'
#     resourceGroupName: ${{ parameters.ResourceGroupName }}
#     location: uksouth
#     templateLocation: 'Linked artifact'
#     csmFile: '$(System.DefaultWorkingDirectory)/groovyws/TemplateForWorkspace.json'
#     csmParametersFile: '$(System.DefaultWorkingDirectory)/groovyws/TemplateParametersForWorkspace.json'
#     deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
   deploymentScope: 'Resource Group'
   azureResourceManagerConnection: clintazrealallrgs
   action: 'Create Or Update Resource Group'
   resourceGroupName: 'factorystuff'
   location:  uksouth
   templateLocation: 'Linked artifact'
   csmFile: $(System.DefaultWorkingDirectory)/MainBicepOrch.bicep
   overrideParameters: '-synapseSqlAdminPassword $(SqlPassword-gh-simplifiedyaml)'
   deploymentMode: 'Incremental'
   deploymentName: 'DeployPipelineTemplate'
   deploymentOutputs: deployment_output

- task:  AzurePowerShell@5
  inputs:
    azureSubscription: clintazrealallrgs
    ScriptType: InlineScript
    Inline: |
            $var=ConvertFrom-Json '$(deployment_output)' 
            $value=$var.synapseWorkspaceName.value 
            Write-Host "##vso[task.setvariable variable=synname;]$value"

# - task: AzureCLI@1
#   displayName: 'Assign role "Synapse Administrator"'
#   inputs:
#     azureSubscription: clintazrealallrgs
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az synapse role assignment create --workspace-name $(deployment_output.synapseWorkspaceName.value) --role "Synapse Administrator" --assignee 4fe7fc36-b425-420f-a3f4-5e14e084eb5e'
#     