# Pipeline to deply Synapse IAC
# Clint Grove. April 2023


trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
 - name: Environment
   type: string
   default: 'Test'
   values:
     - Dev
     - Test
     - Uat

variables:
  - group: ${{parameters.Environment}}-vars

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
   deploymentScope: 'Resource Group'
   azureResourceManagerConnection: clintazrealallrgs
   action: 'Create Or Update Resource Group'
   resourceGroupName: 'factorystuff'
   location:  uksouth
   templateLocation: 'Linked artifact'
   csmFile: $(System.DefaultWorkingDirectory)/MainBicepOrch.bicep
   overrideParameters: '-synapseSqlAdminPassword $(SqlPassword-gh-simplifiedyaml)'
   csmParametersFile: $(System.DefaultWorkingDirectory)/parameters/${{lower(parameters.Environment)}}/bicepparams.json
   deploymentMode: 'Incremental'
   deploymentName: 'DeployPipelineTemplate'
   deploymentOutputs: synapseWorkspaceName


- task: AzureCLI@2
  displayName: 'Assign role "Synapse Administrator"'
  inputs:
    azureSubscription: clintazrealallrgs
    scriptType: bash
    scriptLocation: 'scriptPath'
    scriptPath: '$(System.DefaultWorkingDirectory)/scripts/roleassignAdmin.sh'
    arguments: "groovyws${{lower(parameters.Environment)}} 4fe7fc36-b425-420f-a3f4-5e14e084eb5e"


- task: AzureCLI@2
  displayName: 'Assign role "Synapse Artifact Publisher"'
  inputs:
    azureSubscription: clintazrealallrgs
    scriptType: bash
    scriptLocation: 'scriptPath'
    scriptPath: '$(System.DefaultWorkingDirectory)/scripts/roleassignArtifact.sh'
    arguments: "groovyws${{lower(parameters.Environment)}} b3bd2758-369c-4e4c-8bb6-c2ab93db82ad"