# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
 - name: Environment
   type: string
   default: 'test'
   values:
     - dev
     - test
     - uat

variables:
  - group: Test-vars

steps:

# - task: AzureResourceManagerTemplateDeployment@3
#   inputs:
#    deploymentScope: 'Resource Group'
#    azureResourceManagerConnection: clintazrealallrgs
#    action: 'Create Or Update Resource Group'
#    resourceGroupName: 'factorystuff'
#    location:  uksouth
#    templateLocation: 'Linked artifact'
#    csmFile: $(System.DefaultWorkingDirectory)/MainBicepOrch.bicep
#    overrideParameters: '-synapseSqlAdminPassword $(SqlPassword-gh-simplifiedyaml) -synapseWorkspaceName groovyws${{parameters.Environment}}'
#    deploymentMode: 'Incremental'
#    deploymentName: 'DeployPipelineTemplate'
#    deploymentOutputs: synapseWorkspaceName


- task: AzureCLI@2
  displayName: 'Assign role "Synapse Administrator"'
  inputs:
    azureSubscription: clintazrealallrgs
    scriptType: bash
    scriptLocation: 'scriptPath'
    #inlineScript: 'if(az synapse role assignment create --workspace-name groovywstest --role "Synapse Administrator" --assignee '4fe7fc36-b425-420f-a3f4-5e14e084eb5e'){"yes"}else{"false no"}'
    scriptPath: '$(System.DefaultWorkingDirectory)/scripts/roleassignAdmin.sh'
    arguments: "synapseWS='groovywstest' objectid='4fe7fc36-b425-420f-a3f4-5e14e084eb5e'"


# - task: AzureCLI@1
#   displayName: 'Assign role "Synapse Artifact Publisher"'
#   inputs:
#     azureSubscription: clintazrealallrgs
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az synapse role assignment create --workspace-name groovyws${{parameters.Environment}} --role "Synapse Artifact Publisher" --assignee 4793acfe-f553-46a9-acb6-4495d6e84880'
    