# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - group: Test-vars
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
   deploymentScope: 'Resource Group'
   azureResourceManagerConnection: clintazrealallrgs
   action: 'Create Or Update Resource Group'
   resourceGroupName: 'factorystuff'
   location:  uksouth
   templateLocation: 'Linked artifact'
   csmFile: $(System.DefaultWorkingDirectory)/MainBicepOrch.bicep
   overrideParameters: '-synapseSqlAdminPassword $(SqlPassword-gh-simplifiedyaml)'
   deploymentMode: 'Incremental'
   deploymentName: 'DeployPipelineTemplate'