# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
 - name: Environment
   type: string
   default: 'test'
   values:
     - dev
     - test
     - uat

variables:
  - group: Test-vars

steps:

# - task: AzureResourceManagerTemplateDeployment@3
#   #condition: and(succeed(), eq('${{parameters.doSql}}', 'true'))
#   displayName: "Create ${{ parameters.ServiceReleased}}"
#   inputs:
#     deploymentScope: 'Resource Group'
#     azureResourceManagerConnection: ${{ parameters.ServiceConnection }}
#     subscriptionId: ${{ parameters.SubscriptionId }}
#     action: 'Create Or Update Resource Group'
#     resourceGroupName: ${{ parameters.ResourceGroupName }}
#     location: uksouth
#     templateLocation: 'Linked artifact'
#     csmFile: '$(System.DefaultWorkingDirectory)/groovyws/TemplateForWorkspace.json'
#     csmParametersFile: '$(System.DefaultWorkingDirectory)/groovyws/TemplateParametersForWorkspace.json'
#     deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
   deploymentScope: 'Resource Group'
   azureResourceManagerConnection: clintazrealallrgs
   action: 'Create Or Update Resource Group'
   resourceGroupName: 'factorystuff'
   location:  uksouth
   templateLocation: 'Linked artifact'
   csmFile: $(System.DefaultWorkingDirectory)/MainBicepOrch.bicep
   overrideParameters: '-synapseSqlAdminPassword $(SqlPassword-gh-simplifiedyaml) -synapseWorkspaceName groovyws${{parameters.Environment}}'
   deploymentMode: 'Incremental'
   deploymentName: 'DeployPipelineTemplate'
   deploymentOutputs: synapseWorkspaceName


- task: AzureCLI@1
  displayName: 'Assign role "Synapse Administrator"'
  inputs:
    azureSubscription: clintazrealallrgs
    scriptLocation: 'scriptPath'
    scriptPath: '$(System.DefaultWorkingDirectory)/scripts/roleassign.ps'


# - task: AzureCLI@1
#   displayName: 'Assign role "Synapse Artifact Publisher"'
#   inputs:
#     azureSubscription: clintazrealallrgs
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az synapse role assignment create --workspace-name groovyws${{parameters.Environment}} --role "Synapse Artifact Publisher" --assignee 4793acfe-f553-46a9-acb6-4495d6e84880'
    